name: Build Java Copier EXE

on:
  push:
    branches: [ "main", "master" ] # 当代码推送到 main 或 master 分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的Ubuntu环境来构建

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 建议也将 checkout 升级到 v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '11' # 确保与 pom.xml 中的版本一致
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native executable with Maven
        run: mvn -Pnative package

      - name: Rename executable for Windows
        # GitHub Actions 默认在Linux上构建，文件名没有.exe后缀，我们手动加上
        run: mv target/SmartJavaCopier target/SmartJavaCopier.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # <-- 这里是关键的修正
        with:
          name: SmartJavaCopier-Windows-Executable
          path: target/SmartJavaCopier.exe
